Setup Next.js Client
neogcamp/platform-93by4 pull request #10
Opened 2021-06-28 16:04 UTC by sohamsshah

This PR adds Next.js client structure to the project.

The client has been configured with:
- Next.js
- Chakra UI
- Redux-toolkit

The folder structure and starting pages of the app has been added for the developers to start coding i.e. 
- Pages routes has been added. 
- `api` folder has been deleted since we are running express backend separately on Azure

TODO:
- Components folder structure
- Feature folder (where developers can add redux feature store and slices)

Let me know if any changes are required. Will be swift to reiterate to the comments and improvements.
Thanks

2021-06-29 12:50 UTC, tanaypratap requested changes

2021-06-29 12:50 UTC, tanaypratap commented on client/src/styles/Home.module.css
> +
delete this file

2021-06-29 12:50 UTC, tanaypratap commented on client/src/styles/globals.css
> +body {
delete this file

2021-06-29 12:50 UTC, tanaypratap commented on client/tsconfig.json
> +    "allowJs": true,
why?

2021-06-29 12:50 UTC, tanaypratap commented on client/tsconfig.json
> +    "strict": false,
should have strict true

2021-07-01 05:19 UTC, sohamsshah commented on client/tsconfig.json
> +    "allowJs": true,
This provides flexibility to import JS files in our TS files. Maybe if we need such allowance for the project (due to some library import or else), allowJs should be kept true.

Refer: https://www.typescriptlang.org/tsconfig#allowJs

2021-07-01 05:44 UTC, OmkarK45 approved these changes
Hi Soham, I have reviewed your PR. Everything looks good to me. 👍

2021-07-01 05:44 UTC, OmkarK45 commented on client/src/pages/index.tsx
> +import styles from '../styles/Home.module.css'
Hi Soham!
I think it is OK to delete Home.module.css file as we no longer need it.

2021-07-01 07:18 UTC, uditkumar01 reviewed
Everything is perfect. You can just fix the changes mentioned if possible

2021-07-01 07:18 UTC, uditkumar01 commented on client/src/pages/auth/login.tsx
> +export default function Login() {
the directory isn't correct cause `https://domain.com/auth/login` isn't conventional. Same thing should be corrected for the other routes like `signUp`, `forgot password`.

2021-07-01 07:18 UTC, uditkumar01 commented on client/src/components/Main.tsx
> +import { Text } from "@chakra-ui/react"
Instead of `Main Component` you should create a `Layout Component`as `Main` is of no use but in `Layout` u can add the basic layout of a page needed for every page.

2021-07-01 07:19 UTC, sohamsshah commented on client/src/components/Main.tsx
> +import { Text } from "@chakra-ui/react"
This is temporary. Will resolve it in further PR where we will add components

2021-07-01 07:19 UTC, sohamsshah commented on client/src/pages/auth/login.tsx
> +export default function Login() {
So I shall have `https://domain.com/login` and `https://domain.com/signup`, sort of right?

2021-07-01 07:30 UTC, OmkarK45 commented on client/src/pages/auth/login.tsx
> +export default function Login() {
@sohamsshah It would be better if all of auth pages are put under /auth folder. It will not pollute other pages. 
![image](https://user-images.githubusercontent.com/45557594/124084080-40000b80-da6c-11eb-9a3d-694190086dc6.png)
This is something I'm thinking of doing.

2021-07-01 07:36 UTC, OmkarK45 commented on client/src/pages/auth/login.tsx
> +export default function Login() {
> the directory isn't correct cause `https://domain.com/auth/login` isn't conventional. Same thing should be corrected for the other routes like `signUp`, `forgot password`.

I don't think so. It's a fairly common pattern.

2021-07-01 07:36 UTC, sohamsshah commented on client/src/pages/auth/login.tsx
> +export default function Login() {
Yes. The current structure is this only. For this the routes will be /auth/login and so on.

2021-07-01 09:43 UTC, sohamsshah commented on client/src/pages/auth/login.tsx
> +export default function Login() {
@uditkumar01 @OmkarK45  Merging this right now, if there will be any changes; we can look into that for sure.

2021-07-01 09:55 UTC, merged