Contact page
neogcamp/platform-93by4 pull request #103
Opened 2021-07-14 18:33 UTC by NadaaFarook

Issue #30

2021-07-18 19:05 UTC, uditkumar01 reviewed
Mentioned some minor fixes, please try to fix these.And rest if :100: :fire:

2021-07-18 19:05 UTC, uditkumar01 commented on client/src/pages/contact.tsx
> +              <a href="mailto:contact.neogcamp@gmail.com">
don't use `anchor` tags use chakra `Link` or `NextLink` instead. Not mandatory for now

2021-07-18 19:05 UTC, uditkumar01 commented on client/src/pages/contact.tsx
> +              Have any issue with the platform?
Make a file and get these strings from there.

2021-08-09 12:56 UTC, sohamsshah commented on client/src/pages/contact.tsx
> +              <a href="mailto:contact.neogcamp@gmail.com">
If using href, add target as "_blank" also to it.

2021-08-09 12:57 UTC, sohamsshah commented
@NadaaFarook can you resolve the comments and conflicts, if any?

2021-08-12 09:46 UTC, MehulKChaudhari commented
Good work there, LGTM

2021-08-12 10:32 UTC, sohamsshah requested changes
Everything else looks awesome to me.

2021-08-12 10:32 UTC, sohamsshah commented on client/src/components/StatusCard/StatusCard.tsx
> +            color={status?.color == 'red' ? '#F13C3C' : theme.colors.white}
just curious, shall we consider adding `#F13C3C` to our theme if not present?

2021-08-12 10:32 UTC, sohamsshah commented on client/src/pages/contact.tsx
> +              <a target="_blank" href="mailto:contact.neogcamp@gmail.com">
can we extract the mail href to a constant/string in data folder?

2021-08-12 10:54 UTC, uditkumar01 commented on client/src/pages/contact.tsx
> +              <a target="_blank" href="mailto:contact.neogcamp@gmail.com">
+1 hard coding is not a good practice

2021-08-12 17:00 UTC, MehulKChaudhari commented on client/src/pages/contact.tsx
> +              <a target="_blank" href="mailto:contact.neogcamp@gmail.com">
Agreed it will also follow the consistency

2021-08-14 10:50 UTC, closed without merging