Fix: Schema for the portfolioUrl, Reviewer
neogcamp/platform-93by4 pull request #122
Opened 2021-07-28 14:13 UTC by sushilburagute

# Updated Schema.

2021-07-28 15:07 UTC, prerana1821 requested changes
Hey sushil, great job 💯 
I have suggested some changes. Please let me know if I there is something wrong or can be improved.
Thank you :)

2021-07-28 15:07 UTC, prerana1821 commented on src/models/Portfolio.ts
> +    ],
I guess we can add validation here as well. Also didn't understood what's an author..?
```suggestion
    reviewComments: [
      {
        author: String,
        comment: { type: String, trim: true, minlength: 20 }
        date: Schema.Types.Date,
      },
    ],
```

2021-07-28 15:07 UTC, prerana1821 commented on src/models/Portfolio.ts
>    user: any
Here, I guess instead of `any` we can keep it as `IUser`, because we won't send just an `id` to frontend, we will populate it which means it will become as object as `user` model

```suggestion
  user: IUser
```

2021-07-28 15:12 UTC, sushilburagute commented on src/models/Reviewer.ts
> +    },
Oh, I missed this point. Yup this is supposed to be true. Committing the change.

2021-07-28 15:23 UTC, sushilburagute commented on src/models/Reviewer.ts
> +    },
We discussed this with Tanvi, and we decided to have a single portfolio assigned at a given moment. If we assign 2 -3 portfolios and the reviewer doesn't review them for a couple of days. that wouldn't benefit the user. 

@SAYUK09 what do you think? You're working on the assignment part.

2021-07-29 05:44 UTC, sushilburagute commented on src/models/Portfolio.ts
>  export interface IPortfolioUrl {
Yeah. But the thing is, for the main branch, we've used `IPortfolioUrl` everywhere. We're going to need solid changes in the code if we change this syntax. 

I'm in favor of this change. Once things are more clear on the Data Schema side, we can make this change.

2021-07-29 09:00 UTC, sushilburagute commented on src/models/Portfolio.ts
> +    ],
Adding validation here is a good idea! Hmmm, the Author needs a change in name. I intended to keep it as the comment the admin-reviewer would provide.

2021-07-29 09:14 UTC, SAYUK09 commented on src/models/Reviewer.ts
> +    },
Yes, Discussed this same thing with @prerana1821 
And we thought of keeping it as an array although we just going to pass only 1 portfolio.
Well, I am okay with both of the options.

2021-07-29 09:19 UTC, SAYUK09 commented on src/models/Portfolio.ts
> +    },
Same here,
Didn't quite well understood the purpose of making this an array.
Could you help us here @prerana1821

2021-07-29 14:15 UTC, merged