Uditkumar01/checklist bug fixes
neogcamp/platform-93by4 pull request #166
Opened 2021-08-21 09:37 UTC by uditkumar01

### Fixes
* **Scrolling** issue
* **redirecting user to dashboard** when submission status is under review

2021-08-21 09:54 UTC, SAYUK09 requested changes
Everything seems good. Just have few doubts, commented them.

2021-08-21 09:54 UTC, SAYUK09 commented on src/app.ts
> +}
I guess we aren't supposed to push this file to GitHub right?
Won't this cause merge conflicts and break production?

2021-08-21 09:54 UTC, SAYUK09 commented on client/next.config.js
> +    API_URL: 'http://localhost:5000', // for local development
Do we need to change the `API_URL` back to `https://neog-admissions.azurewebsites.net` before pushing the code?

2021-08-23 08:45 UTC, uditkumar01 commented
Yes, we need to make it compatible with both dev and prod somehow. As it's really cumbersome to change it every time before making a pr.

2021-08-31 04:53 UTC, sushilburagute commented on client/next.config.js
> +    API_URL: 'http://localhost:5000', // for local development
Oh yes. the `API_URL` needs to be that

2021-09-09 16:49 UTC, uditkumar01 commented
Fixed in #191

2021-09-09 16:50 UTC, closed without merging