Interview admission form
neogcamp/platform-93by4 pull request #169
Opened 2021-08-25 19:42 UTC by uditkumar01

### Changes
- Made interview form with validation FE Part.

![image](https://user-images.githubusercontent.com/55291327/130854456-a202a3a9-2c7b-4772-8da5-ea7b226310f1.png)

2021-08-31 06:42 UTC, prerana1821 requested changes
Hey @uditkumar01,
Great work 💯 
I have sugguested few changes please have a look & let me know if you are facing any issues.
Thanks :)

2021-08-31 06:42 UTC, prerana1821 commented on client/src/pages/interview/form.tsx
> +  'discord-id': yup.string().required('Discord id is required.'),
We can also add regex for discord id like how you have added foe phone number.
Regex - /<(.*)#(\d{4})>/g

2021-08-31 06:42 UTC, prerana1821 commented on client/src/pages/interview/form.tsx
> +  'twitter-url': yup.string().required('Twitter url is required.'),
Same for twitter
Regex = /http(?:s)?:\/\/(?:www\.)?twitter\.com\/([a-zA-Z0-9_]+)/g

2021-08-31 06:44 UTC, prerana1821 commented on client/next.config.js
>    env: {
I think we need to comment this & uncomment the below code

2021-08-31 06:49 UTC, sushilburagute requested changes

2021-08-31 07:30 UTC, sohamsshah requested changes
The Code looks good to me! Great work @uditkumar01 
Just have suggested a small refactor.

2021-08-31 07:30 UTC, sohamsshah commented on client/src/pages/submission/checklist.tsx
> +  // scrolling to top of page
We can extract this component out as a separate entity since `scrollToTop` is a common feature required in future pages.

2021-09-01 19:45 UTC, uditkumar01 commented on client/src/pages/interview/form.tsx
> +  'discord-id': yup.string().required('Discord id is required.'),
:+1:

2021-09-04 07:42 UTC, OmkarK45 reviewed
Extremely good work on the form part Udit. It looks good to me.

2021-09-06 12:17 UTC, uditkumar01 commented on client/src/pages/submission/checklist.tsx
> +  // scrolling to top of page
:+1:

2021-09-09 16:37 UTC, uditkumar01 commented
making a new pr after fixing all these changes

2021-09-09 16:37 UTC, closed without merging