Dashboard Changes
neogcamp/platform-93by4 pull request #196
Opened 2021-09-14 12:32 UTC by NadaaFarook

2021-09-17 15:20 UTC, SAYUK09 requested changes
Everything seems fine to me.

2021-09-17 15:20 UTC, SAYUK09 commented on client/src/components/StepCard/StepcardPayment.tsx
> +  //   }
Let clean this if not needed

2021-09-17 15:20 UTC, SAYUK09 commented on client/src/components/StepCard/StepcardPayment.tsx
> +      {/* {status.level == step.level ? (
Same here, we can clean this up

2021-09-21 11:40 UTC, MehulKChaudhari approved these changes
LGTM 🔥

2021-09-21 11:42 UTC, merged