Made design changes
neogcamp/platform-93by4 pull request #28
Opened 2021-07-02 15:13 UTC by NadaaFarook

What features does this PR Address ?
Dashboard UI

What issues this PR solves?
Fixes #2
Added the design changes

Where have you tested it?
Edge ( mobile and desktop responsive)

Quick Demo
![image](https://user-images.githubusercontent.com/59258814/124295085-0d423a00-db76-11eb-92b9-c3dbb03b4121.png)

2021-07-02 18:54 UTC, uditkumar01 commented
looks perfect.

2021-07-03 07:46 UTC, sohamsshah requested changes
Hi Nada, the PR looks good to me. Great work 👏

Just a few suggestions:
- Please remove the `package-lock.json` file. It is probably because you have done `npm i` instead of `yarn`. Due to this file we are getting a lot of unnecssary changes shown in this PR (9000+)
- We have now migrated to `themes` folder as a source for getting all the colors instead of `themeVars` file. Can you refactor your section by changing `themeVars.color.[defined-color]` to `theme.color.[defined-color]`?
- Please remove extra CSS files, if any.

Thanks.

2021-07-03 07:46 UTC, sohamsshah commented on client/src/pages/dashboard/index.tsx
> +          Submission in Neog camp is a 3 step process :{" "}
Can we have this string in `data/strings`?

2021-07-03 07:46 UTC, sohamsshah commented on client/src/components/IntroCard/IntroCard.tsx
> +      className="welcome-section"
why do we have className while we don't have any CSS files?

2021-07-03 09:57 UTC, sushilburagute requested changes
Hey Nada!

Great work on the UI. You've implemented the Mocks with great attention to detail! 
Just a couple of changes and your PR is ready to merge.

2021-07-03 09:57 UTC, sushilburagute commented on client/src/components/IntroCard/IntroCard.tsx
> +      className="welcome-section"
Also, could you please rename this component to `StatusCard.tsx`? Because that's the name we decided in the standup.

2021-07-03 09:57 UTC, sushilburagute commented on client/src/components/StepCard/stepCard.tsx
> +          <ExternalLinkIcon boxSize="30px" m={2} />
Could you please wrap the `<ExternalLinkIcon>` component  in `<a>` tag?

NextJS will prefetch the link making the performance better. Also it would reduce the chances of this breaking in production.

Ref: https://nextjs.org/docs/api-reference/next/link

2021-07-03 14:56 UTC, MehulKChaudhari requested changes
Great job, Just added few changes please into it.

2021-07-03 14:56 UTC, MehulKChaudhari commented on client/src/components/Navbar/Navbar.tsx
>  import { colors } from "../../styles/themeVars/themeVars";
use theme from theme folder instead of themeVars, ThemeVars was initially made. Final one is theme

2021-07-03 14:56 UTC, MehulKChaudhari commented on client/src/components/StatusCard/StatusCard.tsx
> +import React from "react";
we don't need to import react in nextjs.

2021-07-03 14:56 UTC, MehulKChaudhari commented on client/src/components/StepCard/stepCard.tsx
> +import React from "react";
remove this one also

2021-07-03 14:56 UTC, MehulKChaudhari commented on client/src/pages/dashboard/index.tsx
> +                bgColor='black.800'
use `theme.colors.black["800"]` here instead of `black.800`

2021-07-03 17:43 UTC, merged