Sayuri/review portfolio
neogcamp/platform-93by4 pull request #31
Opened 2021-07-03 08:52 UTC by SAYUK09

# Closes #<CORRESPONDING ISSUE NUMBER>

Designed `review-portfolio` page of admin flow.

### Changes

- Created `review-portfolios` page

### Flags

### Screenshots or Video GIFs

####  Desktop View :
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/68416000/124348846-ff3df900-dc09-11eb-91ef-4f60a664c5d1.gif)

####  Mobile View :
![image](https://user-images.githubusercontent.com/68416000/124348532-1380f680-dc08-11eb-8a9b-eb9e6e136088.png)

### Author Checklist
- [x] Vital features and changes captured in unit and/or integration tests
- [ ] Extend the documentation, if necessary
- [x] Merging to `main` from `fork:sayuri/review-portfolio`

2021-07-03 10:38 UTC, prerana1821 requested changes
Hey Sayuri, great job with well written code, I have suggested few changes please do have a look at them & let me know if you have any doubts.
Thank you!

2021-07-03 10:38 UTC, prerana1821 commented on client/src/pages/admin/review-portfolios/index.tsx
> +  function handleInputChange(e: { target: { value: string | number } }) {
- Hey, I guess this is more generic function name, you can name this function something like `addReviewComment` for better readability.
- Also, we can `type` the return type of the function, as its a good practice
```suggestion
  function addReviewComment(e: { target: { value: string | number } }) : void {
```

2021-07-03 10:38 UTC, prerana1821 commented on client/src/pages/admin/review-portfolios/index.tsx
> +            </Box>
This could be a reusable component, so extracting it in a different file would be better.

2021-07-03 10:38 UTC, prerana1821 commented on client/src/pages/admin/review-portfolios/index.tsx
> +                  Application Number : #420
I guess this will be dynamic data, including student name & portfolio link. So, this could come from an object for now.
`{
    applicationNo:'420',
    name:"Tanay Pratap",
    portfolioLink:"https://tanay.netlify.app/"
}`

2021-07-03 11:02 UTC, SAYUK09 commented on client/src/pages/admin/review-portfolios/index.tsx
> +  function handleInputChange(e: { target: { value: string | number } }) {
Much better now. Thanks

2021-07-03 11:09 UTC, SAYUK09 commented on client/src/pages/admin/review-portfolios/index.tsx
> +                  Application Number : #420
Was about to do this. Thanks.

2021-07-04 09:37 UTC, SAYUK09 commented on client/src/pages/admin/review-portfolios/index.tsx
> +            </Box>
Thanks. This a great refactor to do.
Looks much better now and can be reused by all folks

2021-07-05 05:14 UTC, sohamsshah commented
LGTM @SAYUK09

2021-07-05 05:14 UTC, merged